### ISSUE TITLE
.notdef has interpolation issues

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans-flex#566]
It rotates on itself across a few axes.

Solution: copy-paste the default one into every source.

**Comment by octaviopardo** [comment]
seen. We are into it

**Comment by casasin** [comment]
Hi @madig , this should be fixed (tested in our side). Could you double-check and close the issue? Thanks!

**Comment by madig** [comment]
@casasin @MariannaPaszkowska you can check the issue yourself by running the fontbakery and looking for the compatibility check. If it doesn't mention the glyph, you're good.

**Comment by madig** [comment]
According to https://github.com/googlefonts/googlesans-flex/actions/runs/5445310126/jobs/9904373773#step:8:961 (running on the italic branch up to date as of this writing, commit c05b2eaa2), the problem is not yet fixed.

**Comment by octaviopardo** [comment]
Might this be an issue in fontbakery? 

https://github.com/googlefonts/googlesans-flex/assets/2181684/2d91a7b9-0519-45c3-afb0-96c999822551

**Comment by octaviopardo** [comment]
so we are getting this error from 2 ufos that I m gonna look at right now. But 2, not dozens, might it be a problem with the sparse masters, that do not have notdef symbol??
[message.txt](https://github.com/googlefonts/googlesans-flex/files/11938441/message.txt)

**Comment by madig** [comment]
What tool gave that output? And yes, you most probably need to put .notdef into all sparse sources OR remove them from all sources, for technical reasons.

**Comment by casasin** [comment]
I just made a script to quickly check the .notdef points in all the sources. They should be the same as we copy/pasted to all the ufos the same glyph.
The error might come, as you mentioned, from not being in the SPARSE masters. 
It's the same outline excepting that two opsz6 ufos which had an 1/em x shift in one point, but still interpolatable.

**Comment by madig** [comment]
The starting point or some such is different somewhere, so you get cross-overs.

**Comment by madig** [comment]
I pushed a commit to the italics branch that sets the default source's notdef for all sources, plus a script at https://github.com/googlefonts/googlesans-flex/pull/618 to reset it again if need be.

**Comment by casasin** [comment]
> I pushed a commit to the italics branch that sets the default source's notdef for all sources, plus a script at #618 to reset it again if need be.

Great @madig . Thanks!
