### ISSUE TITLE
Interpolation issues in the latest import build

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#810]
[GSF-latest.pdf](https://github.com/googlefonts/googlesans-flex/files/14081667/GSF-latest.pdf)

Affected glyphs:

contour order:
- [x] `yen`

first points:
- [x] `ordmasculine`
- [x] `numbersign` - I am not sure about the issue. The tool shows different starting points, but the interpolation preview looks good. @behdad 
- [x] `eth` @behdad proposed fix doesn't work well here, jfyi

kink:
- [ ] `eth`
- [ ] `five`
- [ ] `five.tf`
- [ ] `s`
- [ ] `section`
- [ ] `uni1E9E ẞ`

**Comment by behdad** [comment]
> * ``
> * [ ]  `numbersign` - I am not sure about the issue. The tool shows different starting points, but the interpolation preview looks good. @behdad
> * [ ]  `eth` @behdad proposed fix doesn't work well here, jfyi

You are right. When one outline is very thin (hairline-like), the tool can easily get confused. Thanks for reporting.

**Comment by octaviopardo** [comment]
fixed yen and ordmasculine.
eth is part of the braced layers glyphs. We are working on it right now, so I proposed we review it again after Wednesday, when the the four glyphs are "finished"

Could I get a hint of the coordinates with the kinks in the other glyphs??

**Comment by behdad** [comment]
> Could I get a hint of the coordinates with the kinks in the other glyphs??

What kind of coordinates would help? Point number, or x/y? I can try to fit that in, but since each page might show multiple kinks, I need to come up with a good UI for it.

**Comment by octaviopardo** [comment]
Sorry, I just realized that the PDF link as on top of the issue. I thouhgt I had to find the spot with the kins and I was asking for help to Marianna. My bad. 

maybe the coordinates of the midway interpolation (axis position) where the issue is found?

**Comment by MariannaPaszkowska** [comment]
@octaviopardo not sure what is happening, but in the latest [import](https://github.com/googlefonts/googlesans-flex/actions/runs/7781836863), I still see all the issues: 
[GSF-latest15.pdf](https://github.com/googlefonts/googlesans-flex/files/14165433/GSF-latest15.pdf)

**Comment by octaviopardo** [comment]
Don t know, but indeed the erros were here again. Fixed them. I ll push a new build later today that will reflect these changes. Several comments though:

- Yen, fixed
- ordmasculine, fixed
- eth; replaced. i m very interested to see if the new eth does return the same kinks
- section, I m gonna be working on it in the next days. I need to remove a point in the spine to reduce the risk of getting this kinks in the interpolation, i ll let you know when it s done
- uni0306, tried a new point structure to see if ti works better
- uni030B, acutecomb and gravecomb. Extremely hard to fix those as the issues happen in  between masters. I recommend reconsidering their point structure for v3.0 to see if we can fix it
- backslash, five, five.tf, S… same, extremely hard to fix those, as the issues happen in between masters. I will review it in the next days
- zero.slash, it was a building component, it wil no longer be exported 
- uni1E9E (germandbls uppercase). Tried a small adjustment, 

later with the build I will check the results and update this entry

**Comment by MariannaPaszkowska** [comment]
Many thanks @octaviopardo ! 🚀  
Major issues have been resolved here: https://github.com/googlefonts/googlesans-flex/pull/844 

Moving the kinks to #803
